/** Shipped NormalApp pj cue-to-asset data. Null cues intentionally remain silent. */
export const UI_SOUND_CATALOG: Readonly<
  Record<string, { key: string; url: string; gain: number } | null>
> = {
  "arg-aleph-absorb": null,
  "arg-aleph-access-whiteout": {
    key: "menu_open_slow_01-ee3ef1",
    url: "/audio/sfx/menu_open_slow_01-ee3ef1.m4a",
    gain: 0.9,
  },
  "arg-aleph-chat-back": {
    key: "return_1-fc3c05",
    url: "/audio/sfx/return_1-fc3c05.m4a",
    gain: 0.8,
  },
  "arg-aleph-chat-toggle": {
    key: "sci_fi_button_click_in_03-50cefb",
    url: "/audio/sfx/sci_fi_button_click_in_03-50cefb.m4a",
    gain: 0.85,
  },
  "arg-aleph-input-focus": {
    key: "radio_button_select_03-57cbe6",
    url: "/audio/sfx/radio_button_select_03-57cbe6.m4a",
    gain: 0.7,
  },
  "arg-aleph-login-cta": {
    key: "door_unlocked_03-3dd603",
    url: "/audio/sfx/door_unlocked_03-3dd603.m4a",
    gain: 1.0,
  },
  "arg-aleph-pill-pick": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.65,
  },
  "arg-aleph-poke-unlock": {
    key: "deny_2-1c4f86",
    url: "/audio/sfx/deny_2-1c4f86.m4a",
    gain: 0.8,
  },
  "arg-aleph-terms-toggle": {
    key: "checkbox_tick_02-618fb1",
    url: "/audio/sfx/checkbox_tick_02-618fb1.m4a",
    gain: 0.8,
  },
  "arg-aleph-voice-reveal": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.5,
  },
  "arg-bounty-detect-bubble": null,
  "arg-bounty-submit-fail": null,
  "arg-bounty-submit-success": null,
  "arg-climax-qte-microgame": null,
  "arg-corruption-climax-leadin": null,
  "arg-corruption-creep-conceal": null,
  "arg-corruption-settle-loom": null,
  "arg-gesture-warning-toast": {
    key: "warning_pop_up_01-fe2ecc",
    url: "/audio/sfx/warning_pop_up_01-fe2ecc.m4a",
    gain: 1.0,
  },
  "arg-glitch-burst-story": {
    key: "crafting_fail_01-abf6f8",
    url: "/audio/sfx/crafting_fail_01-abf6f8.m4a",
    gain: 1.05,
  },
  "arg-locked-file-denied": null,
  "arg-qfr-dock-running": null,
  "arg-qfr-splash-refuse": {
    key: "deny_1-1d4f88",
    url: "/audio/sfx/deny_1-1d4f88.m4a",
    gain: 0.8,
  },
  "arg-recovery-complete-toast": null,
  "arg-vault-unlock-success": null,
  "arg-vault-wrong-shake": null,
  "arg-void-glitch-ambient": null,
  "boardgames-chess-check-checkmate": {
    key: "wooden_button_01-0cbcd2",
    url: "/audio/sfx/wooden_button_01-0cbcd2.m4a",
    gain: 1.0,
  },
  "boardgames-chess-illegal-move": {
    key: "deny_1-1d4f88",
    url: "/audio/sfx/deny_1-1d4f88.m4a",
    gain: 1.0,
  },
  "boardgames-chess-move-place": {
    key: "wooden_button_click_in_05-4676cb",
    url: "/audio/sfx/wooden_button_click_in_05-4676cb.m4a",
    gain: 1.0,
  },
  "boardgames-chess-nori-request-sheet": {
    key: "prompt_1-35ad68",
    url: "/audio/sfx/prompt_1-35ad68.m4a",
    gain: 1.0,
  },
  "boardgames-chess-piece-pickup": {
    key: "item_drag_01-c6766a",
    url: "/audio/sfx/item_drag_01-c6766a.m4a",
    gain: 0.6,
  },
  "boardgames-chess-promotion-dialog": {
    key: "inventory_open_03-22f80e",
    url: "/audio/sfx/inventory_open_03-22f80e.m4a",
    gain: 1.0,
  },
  "boardgames-chess-response-toast": {
    key: "notification_1-aafb8e",
    url: "/audio/sfx/notification_1-aafb8e.m4a",
    gain: 1.0,
  },
  "boardgames-codenames-agent-card-land": {
    key: "item_acquired_long_04-1e3f30",
    url: "/audio/sfx/item_acquired_long_04-1e3f30.m4a",
    gain: 0.9,
  },
  "boardgames-codenames-assassin-reveal": {
    key: "error_01-607ec3",
    url: "/audio/sfx/error_01-607ec3.m4a",
    gain: 1.15,
  },
  "boardgames-codenames-bystander-card-land": {
    key: "button_click_rejection_11-a7dc06",
    url: "/audio/sfx/button_click_rejection_11-a7dc06.m4a",
    gain: 1.0,
  },
  "boardgames-codenames-card-hover": {
    key: "hover_1-f02a15",
    url: "/audio/sfx/hover_1-f02a15.m4a",
    gain: 0.5,
  },
  "boardgames-codenames-card-shake-suspense": {
    key: "menu_open_very_slow_01-327e8f",
    url: "/audio/sfx/menu_open_very_slow_01-327e8f.m4a",
    gain: 0.7,
  },
  "boardgames-codenames-clue-given": {
    key: "notification_4-affb96",
    url: "/audio/sfx/notification_4-affb96.m4a",
    gain: 1.0,
  },
  "boardgames-codenames-end-turn": {
    key: "wooden_button_click_out_07-5e3b93",
    url: "/audio/sfx/wooden_button_click_out_07-5e3b93.m4a",
    gain: 1.0,
  },
  "boardgames-codenames-game-start": {
    key: "game_state_change_03-f0678b",
    url: "/audio/sfx/game_state_change_03-f0678b.m4a",
    gain: 1.0,
  },
  "boardgames-codenames-lose-overlay": {
    key: "debuff_applied_02-b588fd",
    url: "/audio/sfx/debuff_applied_02-b588fd.m4a",
    gain: 1.0,
  },
  "boardgames-codenames-sudden-death-overlay": {
    key: "debuff_applied_06-b188f6",
    url: "/audio/sfx/debuff_applied_06-b188f6.m4a",
    gain: 1.1,
  },
  "boardgames-codenames-tap-to-confirm": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.7,
  },
  "boardgames-codenames-turn-overlay": {
    key: "game_state_change_01-f2678e",
    url: "/audio/sfx/game_state_change_01-f2678e.m4a",
    gain: 1.0,
  },
  "boardgames-codenames-win-overlay": {
    key: "mission_success_06-6833db",
    url: "/audio/sfx/mission_success_06-6833db.m4a",
    gain: 1.1,
  },
  "comms-mail-arrival": {
    key: "notification_14-8b3a0e",
    url: "/audio/sfx/notification_14-8b3a0e.m4a",
    gain: 1.1,
  },
  "comms-mail-attachment-downloaded": {
    key: "item_acquired_03-bae178",
    url: "/audio/sfx/item_acquired_03-bae178.m4a",
    gain: 1.05,
  },
  "comms-mail-compose-refused": {
    key: "error_message_05-f62d41",
    url: "/audio/sfx/error_message_05-f62d41.m4a",
    gain: 1.0,
  },
  "comms-mail-open-email": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.6,
  },
  "comms-norichat-chip-refuse": {
    key: "error_message_05-f62d41",
    url: "/audio/sfx/error_message_05-f62d41.m4a",
    gain: 0.9,
  },
  "comms-norichat-chip-toggle": {
    key: "sci_fi_button_click_in_01-4ecef8",
    url: "/audio/sfx/sci_fi_button_click_in_01-4ecef8.m4a",
    gain: 0.9,
  },
  "comms-norichat-focus": {
    key: "radio_button_select_03-57cbe6",
    url: "/audio/sfx/radio_button_select_03-57cbe6.m4a",
    gain: 0.8,
  },
  "comms-norichat-receive": null,
  "comms-norichat-send": null,
  "comms-notify-click-through": {
    key: "soft-bubbly_button_click_in_02-af1f64",
    url: "/audio/sfx/soft-bubbly_button_click_in_02-af1f64.m4a",
    gain: 1.0,
  },
  "comms-notify-deferred-flush": {
    key: "notification_06-8b37cf",
    url: "/audio/sfx/notification_06-8b37cf.m4a",
    gain: 1.0,
  },
  "comms-notify-dismiss": {
    key: "menu_close_03-2dde05",
    url: "/audio/sfx/menu_close_03-2dde05.m4a",
    gain: 0.7,
  },
  "comms-notify-toast-in": {
    key: "notification_06-8b37cf",
    url: "/audio/sfx/notification_06-8b37cf.m4a",
    gain: 0.9,
  },
  "comms-signal-arrival": {
    key: "notification_14-8b3a0e",
    url: "/audio/sfx/notification_14-8b3a0e.m4a",
    gain: 1.05,
  },
  "comms-signal-auth-error": {
    key: "error_message_05-f62d41",
    url: "/audio/sfx/error_message_05-f62d41.m4a",
    gain: 0.9,
  },
  "comms-signal-bot-reply": {
    key: "button_click_10-5e7759",
    url: "/audio/sfx/button_click_10-5e7759.m4a",
    gain: 0.6,
  },
  "comms-signal-evidence-unlock": {
    key: "buff_applied_10-4c8848",
    url: "/audio/sfx/buff_applied_10-4c8848.m4a",
    gain: 1.1,
  },
  "comms-signal-login-success": {
    key: "crafting_success_04-777ff2",
    url: "/audio/sfx/crafting_success_04-777ff2.m4a",
    gain: 1.05,
  },
  "comms-signal-open-thread": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.65,
  },
  "comms-signal-recovery-accepted": {
    key: "checkbox_tick_04-638fb5",
    url: "/audio/sfx/checkbox_tick_04-638fb5.m4a",
    gain: 1.0,
  },
  "comms-signal-sealed-composer": {
    key: "button_click_rejection_20-b8e2dc",
    url: "/audio/sfx/button_click_rejection_20-b8e2dc.m4a",
    gain: 0.9,
  },
  "comms-signal-typing": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.5,
  },
  "comms-signal-verify-send": {
    key: "liquid_button_05-8a0fde",
    url: "/audio/sfx/liquid_button_05-8a0fde.m4a",
    gain: 0.8,
  },
  "cutscenes-cg-touch-pulse": null,
  "cutscenes-coldopen-shatter": null,
  "cutscenes-corruption-erupt": {
    key: "dramatic_button_01-3a6598",
    url: "/audio/sfx/dramatic_button_01-3a6598.m4a",
    gain: 1.15,
  },
  "cutscenes-datasea-message-land": {
    key: "chat_message_received_03-5ebcc8",
    url: "/audio/sfx/chat_message_received_03-5ebcc8.m4a",
    gain: 0.8,
  },
  "cutscenes-datasea-typing-dots": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.5,
  },
  "cutscenes-datasea-whiteout": null,
  "cutscenes-entry-console-alarm": {
    key: "error_message_06-f32d3c",
    url: "/audio/sfx/error_message_06-f32d3c.m4a",
    gain: 0.7,
  },
  "cutscenes-farewell-hard-cut": null,
  "cutscenes-memory-bubble-reveal": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.7,
  },
  "cutscenes-memory-window-pop": {
    key: "soft-bubbly_button_click_out_02-518d33",
    url: "/audio/sfx/soft-bubbly_button_click_out_02-518d33.m4a",
    gain: 0.7,
  },
  "cutscenes-microgame-hit": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.6,
  },
  "cutscenes-microgame-solve": {
    key: "glitch_023-ed1184",
    url: "/audio/sfx/glitch_023-ed1184.m4a",
    gain: 1.0,
  },
  "cutscenes-microgame-solve-finale": {
    key: "glitch_071-7b0a14",
    url: "/audio/sfx/glitch_071-7b0a14.m4a",
    gain: 1.0,
  },
  "cutscenes-monologue-typewriter": {
    key: "typing_1-ab1d82",
    url: "/audio/sfx/typing_1-ab1d82.m4a",
    gain: 0.5,
  },
  "cutscenes-popup-spam-notify": {
    key: "notification_06-8b37cf",
    url: "/audio/sfx/notification_06-8b37cf.m4a",
    gain: 0.8,
  },
  "cutscenes-rhythm-beat-feedback": {
    key: "button_click_rejection_09-b3de57",
    url: "/audio/sfx/button_click_rejection_09-b3de57.m4a",
    gain: 0.85,
  },
  "cutscenes-tap-to-wake": {
    key: "shine-736d5d",
    url: "/audio/sfx/shine-736d5d.m4a",
    gain: 1.15,
  },
  "cutscenes-virus-all-clear": {
    key: "level_up_06-696fc3",
    url: "/audio/sfx/level_up_06-696fc3.m4a",
    gain: 1.1,
  },
  "cutscenes-virus-bar-fill": null,
  "cutscenes-virus-window-spawn": {
    key: "glitch_016-020f66",
    url: "/audio/sfx/glitch_016-020f66.m4a",
    gain: 1.0,
  },
  "cutscenes-wave-spawn": {
    key: "glitch_016-020f66",
    url: "/audio/sfx/glitch_016-020f66.m4a",
    gain: 0.8,
  },
  "cutscenes-wave-surge": {
    key: "game_state_change_03-f0678b",
    url: "/audio/sfx/game_state_change_03-f0678b.m4a",
    gain: 1.1,
  },
  "idle-abdicate-commit": {
    key: "game_state_change_06-ed6786",
    url: "/audio/sfx/game_state_change_06-ed6786.m4a",
    gain: 1.1,
  },
  "idle-alignment-commit": {
    key: "game_state_change_03-f0678b",
    url: "/audio/sfx/game_state_change_03-f0678b.m4a",
    gain: 1.1,
  },
  "idle-boot-charge": null,
  "idle-boot-ignite": null,
  "idle-boot-line": {
    key: "radio_button_select_01-59cbe9",
    url: "/audio/sfx/radio_button_select_01-59cbe9.m4a",
    gain: 0.45,
  },
  "idle-boot-out": {
    key: "menu_open_fast_03-327582",
    url: "/audio/sfx/menu_open_fast_03-327582.m4a",
    gain: 0.7,
  },
  "idle-boot-shine": {
    key: "crafting_success_05-767ff0",
    url: "/audio/sfx/crafting_success_05-767ff0.m4a",
    gain: 0.7,
  },
  "idle-boot-stamp": {
    key: "wooden_button_01-0cbcd2",
    url: "/audio/sfx/wooden_button_01-0cbcd2.m4a",
    gain: 0.9,
  },
  "idle-buy-mode-switch": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.8,
  },
  "idle-cap-reached": {
    key: "debuff_applied_07-b288f8",
    url: "/audio/sfx/debuff_applied_07-b288f8.m4a",
    gain: 0.95,
  },
  "idle-click-combo": null,
  "idle-click-crit": {
    key: "button_click_10-5e7759",
    url: "/audio/sfx/button_click_10-5e7759.m4a",
    gain: 0.85,
  },
  "idle-coin-drop": null,
  "idle-core-click": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.6,
  },
  "idle-equilibrium-commit": {
    key: "dramatic_button_02-3b659a",
    url: "/audio/sfx/dramatic_button_02-3b659a.m4a",
    gain: 0.72,
  },
  "idle-generator-buy": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.8,
  },
  "idle-generator-first-online": {
    key: "menu_open_fast_03-327582",
    url: "/audio/sfx/menu_open_fast_03-327582.m4a",
    gain: 1.05,
  },
  "idle-lucky-jackpot": {
    key: "currency_gained-970b6f",
    url: "/audio/sfx/currency_gained-970b6f.m4a",
    gain: 1.0,
  },
  "idle-memento-claim": {
    key: "chat_message_received_05-60bccb",
    url: "/audio/sfx/chat_message_received_05-60bccb.m4a",
    gain: 0.9,
  },
  "idle-memento-complete": {
    key: "quest_completed_01-c37498",
    url: "/audio/sfx/quest_completed_01-c37498.m4a",
    gain: 1.1,
  },
  "idle-paradigm-reveal-toast": {
    key: "menu_open_fast_03-327582",
    url: "/audio/sfx/menu_open_fast_03-327582.m4a",
    gain: 0.9,
  },
  "idle-popup-toggle": {
    key: "menu_close_03-2dde05",
    url: "/audio/sfx/menu_close_03-2dde05.m4a",
    gain: 0.6,
  },
  "idle-skill-fire": {
    key: "soft-bubbly_button_click_out_03-508d31",
    url: "/audio/sfx/soft-bubbly_button_click_out_03-508d31.m4a",
    gain: 1.0,
  },
  "idle-skill-ready": null,
  "idle-upgrade-buy": {
    key: "button_click_rejection_09-b3de57",
    url: "/audio/sfx/button_click_rejection_09-b3de57.m4a",
    gain: 1.0,
  },
  "partygames-cakeduel-banner-whoosh": {
    key: "swipe_03-6247f7",
    url: "/audio/sfx/swipe_03-6247f7.m4a",
    gain: 0.55,
  },
  "partygames-cakeduel-bout-result": {
    key: "item_acquired_long_03-233f38",
    url: "/audio/sfx/item_acquired_long_03-233f38.m4a",
    gain: 1.0,
  },
  "partygames-cakeduel-cake-transfer": {
    key: "item_drop_03-75891b",
    url: "/audio/sfx/item_drop_03-75891b.m4a",
    gain: 1.0,
  },
  "partygames-cakeduel-card-draw": {
    key: "item_drag_01-c6766a",
    url: "/audio/sfx/item_drag_01-c6766a.m4a",
    gain: 0.75,
  },
  "partygames-cakeduel-card-play": {
    key: "item_drop_07-798921",
    url: "/audio/sfx/item_drop_07-798921.m4a",
    gain: 0.85,
  },
  "partygames-cakeduel-card-select": null,
  "partygames-cakeduel-challenge": {
    key: "item_equip_04-8900bb",
    url: "/audio/sfx/item_equip_04-8900bb.m4a",
    gain: 1.1,
  },
  "partygames-cakeduel-challenge-reveal": {
    key: "game_state_change_12-6f6481",
    url: "/audio/sfx/game_state_change_12-6f6481.m4a",
    gain: 0.9,
  },
  "partygames-cakeduel-hand-reorder": {
    key: "item_drag_08-bf765f",
    url: "/audio/sfx/item_drag_08-bf765f.m4a",
    gain: 0.55,
  },
  "partygames-cakeduel-victory-defeat": {
    key: "mission_success_01-6733d9",
    url: "/audio/sfx/mission_success_01-6733d9.m4a",
    gain: 1.15,
  },
  "partygames-cakeduel-wolfy-taunt": null,
  "partygames-pictionary-correct-answer": {
    key: "item_acquired_03-bae178",
    url: "/audio/sfx/item_acquired_03-bae178.m4a",
    gain: 1.05,
  },
  "partygames-pictionary-hint-reveal": {
    key: "button_click_10-5e7759",
    url: "/audio/sfx/button_click_10-5e7759.m4a",
    gain: 0.7,
  },
  "partygames-pictionary-next-round-countdown": {
    key: "navigation_04-02d74b",
    url: "/audio/sfx/navigation_04-02d74b.m4a",
    gain: 0.8,
  },
  "partygames-pictionary-pen-scratch": {
    key: "dialogue_loop_1-ed7ac7",
    url: "/audio/sfx/dialogue_loop_1-ed7ac7.m4a",
    gain: 0.5,
  },
  "partygames-pictionary-skip-round": {
    key: "item_split_02-673fe3",
    url: "/audio/sfx/item_split_02-673fe3.m4a",
    gain: 1.0,
  },
  "partygames-pictionary-timer-low": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.5,
  },
  "partygames-pictionary-tools": {
    key: "wooden_button_click_in_08-4976cf",
    url: "/audio/sfx/wooden_button_click_in_08-4976cf.m4a",
    gain: 1.0,
  },
  "partygames-pictionary-wrong-guess": {
    key: "dialogue_loop_1-ed7ac7",
    url: "/audio/sfx/dialogue_loop_1-ed7ac7.m4a",
    gain: 0.75,
  },
  "partygames-session-start": {
    key: "start_1-4606b6",
    url: "/audio/sfx/start_1-4606b6.m4a",
    gain: 1.1,
  },
  "primitives-button-press": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.75,
  },
  "primitives-card-drag": null,
  "primitives-card-flip": null,
  "primitives-card-hover": null,
  "primitives-error-shake": null,
  "primitives-input-focus": {
    key: "radio_button_select_03-57cbe6",
    url: "/audio/sfx/radio_button_select_03-57cbe6.m4a",
    gain: 0.8,
  },
  "primitives-input-submit": {
    key: "swipe_10-c94ad8",
    url: "/audio/sfx/swipe_10-c94ad8.m4a",
    gain: 0.8,
  },
  "primitives-input-typing": {
    key: "typing_1-ab1d82",
    url: "/audio/sfx/typing_1-ab1d82.m4a",
    gain: 0.5,
  },
  "primitives-menu-item-select": {
    key: "radio_button_select_03-57cbe6",
    url: "/audio/sfx/radio_button_select_03-57cbe6.m4a",
    gain: 0.8,
  },
  "primitives-menu-open": {
    key: "menu_open_fast_03-327582",
    url: "/audio/sfx/menu_open_fast_03-327582.m4a",
    gain: 0.7,
  },
  "primitives-nav-select": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.65,
  },
  "primitives-sheet-dismiss": {
    key: "menu_close_03-2dde05",
    url: "/audio/sfx/menu_close_03-2dde05.m4a",
    gain: 0.9,
  },
  "primitives-sheet-open": {
    key: "menu_open_fast_03-327582",
    url: "/audio/sfx/menu_open_fast_03-327582.m4a",
    gain: 1.0,
  },
  "primitives-slider-drag": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.5,
  },
  "primitives-switch-toggle": {
    key: "toggle_switch_02-183a5c",
    url: "/audio/sfx/toggle_switch_02-183a5c.m4a",
    gain: 1.0,
  },
  "primitives-tooltip-show": null,
  "shell-boot-chrome-reveal": null,
  "shell-dock-damaged-veto": {
    key: "deny_1-1d4f88",
    url: "/audio/sfx/deny_1-1d4f88.m4a",
    gain: 0.8,
  },
  "shell-dock-download-complete": {
    key: "objective_reached_02-573d50",
    url: "/audio/sfx/objective_reached_02-573d50.m4a",
    gain: 1.1,
  },
  "shell-dock-press": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.55,
  },
  "shell-exclusive-enter": {
    key: "inventory_open_06-25f813",
    url: "/audio/sfx/inventory_open_06-25f813.m4a",
    gain: 0.8,
  },
  "shell-exclusive-exit": {
    key: "inventory_open_03-22f80e",
    url: "/audio/sfx/inventory_open_03-22f80e.m4a",
    gain: 1.0,
  },
  "shell-maximize-toggle": {
    key: "soft-bubbly_button_click_out_04-578d3c",
    url: "/audio/sfx/soft-bubbly_button_click_out_04-578d3c.m4a",
    gain: 0.8,
  },
  "shell-menu-open": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.55,
  },
  "shell-nori-pat-complete": null,
  "shell-nori-pat-press": null,
  "shell-nori-pat-stroke": null,
  "shell-notification-dismiss": null,
  "shell-notification-toast": null,
  "shell-session-reconnected": null,
  "shell-snap-commit": {
    key: "item_drop_07-798921",
    url: "/audio/sfx/item_drop_07-798921.m4a",
    gain: 1.0,
  },
  "shell-snap-preview-engage": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.5,
  },
  "shell-snap-tearoff": {
    key: "item_drop_02-74891a",
    url: "/audio/sfx/item_drop_02-74891a.m4a",
    gain: 1.0,
  },
  "shell-window-close": {
    key: "menu_close_03-2dde05",
    url: "/audio/sfx/menu_close_03-2dde05.m4a",
    gain: 0.8,
  },
  "shell-window-focus": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.45,
  },
  "shell-window-minimize": {
    key: "menu_open_fast_03-327582",
    url: "/audio/sfx/menu_open_fast_03-327582.m4a",
    gain: 0.85,
  },
  "shell-window-open": {
    key: "soft-bubbly_button_click_out_02-518d33",
    url: "/audio/sfx/soft-bubbly_button_click_out_02-518d33.m4a",
    gain: 0.85,
  },
  "shell-window-restore": {
    key: "menu_open_fast_04-39758d",
    url: "/audio/sfx/menu_open_fast_04-39758d.m4a",
    gain: 1.0,
  },
  "webapps-bounty-detect-bubble": {
    key: "soft_bubbly_button_02-706f97",
    url: "/audio/sfx/soft_bubbly_button_02-706f97.m4a",
    gain: 1.0,
  },
  "webapps-bounty-jackpot": {
    key: "achievement_unlocked_02-8e2c79",
    url: "/audio/sfx/achievement_unlocked_02-8e2c79.m4a",
    gain: 0.8,
  },
  "webapps-bounty-submit-fail": {
    key: "button_click_rejection_11-a7dc06",
    url: "/audio/sfx/button_click_rejection_11-a7dc06.m4a",
    gain: 1.0,
  },
  "webapps-bounty-submit-success": {
    key: "purchase_success_01-1c9efc",
    url: "/audio/sfx/purchase_success_01-1c9efc.m4a",
    gain: 1.0,
  },
  "webapps-browser-bookmark": {
    key: "notification_1-aafb8e",
    url: "/audio/sfx/notification_1-aafb8e.m4a",
    gain: 1.0,
  },
  "webapps-browser-download-complete": {
    key: "item_acquired_03-bae178",
    url: "/audio/sfx/item_acquired_03-bae178.m4a",
    gain: 1.0,
  },
  "webapps-browser-navigate": {
    key: "button_click_03-61799c",
    url: "/audio/sfx/button_click_03-61799c.m4a",
    gain: 0.55,
  },
  "webapps-browser-page-error": null,
  "webapps-browser-tab-close": {
    key: "menu_close_03-2dde05",
    url: "/audio/sfx/menu_close_03-2dde05.m4a",
    gain: 0.7,
  },
  "webapps-browser-tab-open": {
    key: "radio_button_select_03-57cbe6",
    url: "/audio/sfx/radio_button_select_03-57cbe6.m4a",
    gain: 0.7,
  },
  "webapps-files-locked-file": {
    key: "error_message_05-f62d41",
    url: "/audio/sfx/error_message_05-f62d41.m4a",
    gain: 0.9,
  },
  "webapps-files-open-folder": {
    key: "button_click_08-6c79ad",
    url: "/audio/sfx/button_click_08-6c79ad.m4a",
    gain: 0.75,
  },
  "webapps-files-recovery-complete": {
    key: "objective_reached_02-573d50",
    url: "/audio/sfx/objective_reached_02-573d50.m4a",
    gain: 1.05,
  },
  "webapps-files-vault-unlock": {
    key: "door_unlocked_01-3bd600",
    url: "/audio/sfx/door_unlocked_01-3bd600.m4a",
    gain: 1.1,
  },
  "webapps-files-vault-wrong-pass": {
    key: "button_click_rejection_22-bae2e0",
    url: "/audio/sfx/button_click_rejection_22-bae2e0.m4a",
    gain: 0.9,
  },
  "webapps-preview-zoom": {
    key: "button_click_09-6b79ac",
    url: "/audio/sfx/button_click_09-6b79ac.m4a",
    gain: 0.6,
  },
  "webapps-qfr-keygen-splash": null,
  "webapps-terminal-command-run": {
    key: "radio_button_select_01-59cbe9",
    url: "/audio/sfx/radio_button_select_01-59cbe9.m4a",
    gain: 0.85,
  },
  "webapps-terminal-error": {
    key: "deny_1-1d4f88",
    url: "/audio/sfx/deny_1-1d4f88.m4a",
    gain: 0.8,
  },
  "webapps-terminal-keystroke": {
    key: "typing_2-ae1d87",
    url: "/audio/sfx/typing_2-ae1d87.m4a",
    gain: 0.5,
  },
  "webapps-terminal-ssh-connect": {
    key: "crafting_success_05-767ff0",
    url: "/audio/sfx/crafting_success_05-767ff0.m4a",
    gain: 1.05,
  },
  "chess.gameStart": {
    key: "chess.gameStart",
    url: "/audio/chess/game-start.mp3",
    gain: 0.9,
  },
  "chess.gameEnd": {
    key: "chess.gameEnd",
    url: "/audio/chess/game-end.mp3",
    gain: 0.9,
  },
  "chess.moveSelf": {
    key: "chess.moveSelf",
    url: "/audio/sfx/wooden_button_click_in_05-4676cb.m4a",
    gain: 0.9,
  },
  "chess.moveOpponent": {
    key: "chess.moveOpponent",
    url: "/audio/sfx/wooden_button_click_in_05-4676cb.m4a",
    gain: 0.9,
  },
  "chess.capture": {
    key: "chess.capture",
    url: "/audio/chess/capture.mp3",
    gain: 0.9,
  },
  "chess.castle": {
    key: "chess.castle",
    url: "/audio/chess/castle.mp3",
    gain: 0.9,
  },
  "chess.check": {
    key: "chess.check",
    url: "/audio/sfx/wooden_button_01-0cbcd2.m4a",
    gain: 0.9,
  },
  "chess.promote": {
    key: "chess.promote",
    url: "/audio/chess/promote.mp3",
    gain: 0.9,
  },
  "chess.illegal": {
    key: "chess.illegal",
    url: "/audio/sfx/deny_1-1d4f88.m4a",
    gain: 0.9,
  },
};
