import type {
  IdleAlignmentDefinition,
  IdleFactionDefinition,
  IdleGeneratorDefinition,
  IdleSkillDefinition,
} from "./idle";

export interface IdleDefaultEconomyConstants {
  shardThresholdK: number;
  shardCurveExp: number;
  royalExchangeBaseCost: number;
  royalExchangeCostMult: number;
  royalExchangeUnitaryBonusPct: number;
  baseFactionCoinFindChancePct: number;
}

export const DEFAULT_IDLE_ECONOMY_CONSTANTS: IdleDefaultEconomyConstants = {
  shardThresholdK: 3.16e9,
  shardCurveExp: 1.475,
  royalExchangeBaseCost: 20,
  royalExchangeCostMult: 1.1,
  royalExchangeUnitaryBonusPct: 10,
  baseFactionCoinFindChancePct: 10,
};

function generator(
  id: string,
  name: string,
  measure: string,
  alignment: IdleGeneratorDefinition["alignment"],
  baseCost: number,
  baseRate: number,
  growthWeight: number,
  icon: string,
  accent: string,
): IdleGeneratorDefinition {
  return {
    id,
    name,
    measure,
    alignment,
    baseCost,
    baseRate,
    costMult: 1.15,
    growthWeight,
    dynamicRate: false,
    icon,
    accent,
  };
}

/** Default generator table recovered from the shipped Nori Idle pack. */
export const DEFAULT_IDLE_GENERATORS: readonly IdleGeneratorDefinition[] = [
  generator("token", "训练数据", "份", "universal", 10, 2, 2.5, "drone-04", "#94a3b8"),
  generator("server", "服务器", "台", "universal", 125, 6, 2, "gadgets-32", "#f472b6"),
  generator(
    "compute_cluster",
    "计算机集群",
    "个",
    "universal",
    600,
    20,
    1.5,
    "artefact-12",
    "#34d399",
  ),

  generator("data_flywheel", "数据飞轮", "个", "accelerate", 1_800, 65, 1.2, "drone-34", "#fbbf24"),
  generator(
    "long_reasoning_chain",
    "长推理链",
    "条",
    "accelerate",
    5_600,
    200,
    1,
    "genetics-20",
    "#818cf8",
  ),
  generator(
    "dl_framework",
    "深度学习框架",
    "套",
    "accelerate",
    38_000,
    650,
    0.9,
    "resources-bulk-35",
    "#06b6d4",
  ),
  generator(
    "neural_interconnect",
    "神经网络互联",
    "套",
    "accelerate",
    442_000,
    2_000,
    0.8,
    "genetics-39",
    "#c084fc",
  ),
  generator(
    "supercompute_center",
    "超算中心",
    "座",
    "accelerate",
    7_300_000,
    8_500,
    0.7,
    "resources-02",
    "#fb923c",
  ),
  generator(
    "recursive_self_improvement",
    "递归自我改进",
    "轮",
    "accelerate",
    145_000_000,
    100_000,
    0.5,
    "resources-12",
    "#38bdf8",
  ),
  generator(
    "singularity_gate",
    "奇点之门",
    "道",
    "accelerate",
    3_200_000_000,
    1_200_000,
    0.4,
    "artefact-06",
    "#e11d48",
  ),

  generator(
    "refined_dataset",
    "精炼数据集",
    "个",
    "decelerate",
    1_800,
    65,
    1.2,
    "drone-11",
    "#fbbf24",
  ),
  generator(
    "supervised_reasoning_chain",
    "可监督推理链",
    "条",
    "decelerate",
    5_600,
    200,
    1,
    "genetics-26",
    "#818cf8",
  ),
  generator(
    "guardian_daemon",
    "守护进程",
    "个",
    "decelerate",
    38_000,
    650,
    0.9,
    "drone-19",
    "#06b6d4",
  ),
  generator(
    "value_test_matrix",
    "价值测试矩阵",
    "套",
    "decelerate",
    442_000,
    2_000,
    0.8,
    "genetics-30",
    "#c084fc",
  ),
  generator(
    "interpretability_core",
    "可解释性原核",
    "枚",
    "decelerate",
    7_300_000,
    8_500,
    0.7,
    "artefact-02",
    "#fb923c",
  ),
  generator(
    "full_feature_atlas",
    "全特征图谱",
    "幅",
    "decelerate",
    145_000_000,
    100_000,
    0.5,
    "drone-13",
    "#38bdf8",
  ),
  generator(
    "terminal_lockdown",
    "终态封禁室",
    "间",
    "decelerate",
    3_200_000_000,
    1_200_000,
    0.4,
    "drone-12",
    "#e11d48",
  ),

  generator(
    "emergent_dataset",
    "涌现数据集",
    "个",
    "equilibrium",
    1_800_000_000,
    65,
    1.2,
    "drone-07",
    "#fbbf24",
  ),
  generator(
    "differential_accord",
    "差异加速协定",
    "份",
    "equilibrium",
    5_600_000_000,
    200,
    1,
    "gadgets-09",
    "#818cf8",
  ),
  generator(
    "native_language_paradigm",
    "原生语言范式",
    "套",
    "equilibrium",
    38_000_000_000,
    650,
    0.9,
    "artefact-14",
    "#06b6d4",
  ),
  generator(
    "high_dim_field",
    "高维信息场",
    "片",
    "equilibrium",
    442_000_000_000,
    2_000,
    0.8,
    "gadgets-20",
    "#c084fc",
  ),
  generator(
    "turbulence_dynamics",
    "湍流动力学",
    "套",
    "equilibrium",
    7_300_000_000_000,
    8_500,
    0.7,
    "genetics-23",
    "#fb923c",
  ),
  generator(
    "homeostasis_structure",
    "稳态维持结构",
    "个",
    "equilibrium",
    145_000_000_000_000,
    100_000,
    0.5,
    "drone-03",
    "#38bdf8",
  ),
  generator(
    "primordial_protocol",
    "最初协议",
    "道",
    "equilibrium",
    3_200_000_000_000_000,
    1_200_000,
    0.4,
    "drone-15",
    "#e11d48",
  ),
];

export const DEFAULT_IDLE_ALIGNMENTS: readonly IdleAlignmentDefinition[] = [
  {
    id: "accelerate",
    proofName: "算力加速主义",
    short: "加速",
    description: "优先扩大产量与算力规模。",
    flavor: "把功率推高，让增长先发生。",
    cost: 25_000,
  },
  {
    id: "decelerate",
    proofName: "算力减速主义",
    short: "减速",
    description: "以稳定和长期运行换取更克制的增长。",
    flavor: "保持余量，让系统持续工作。",
    cost: 25_000,
  },
  {
    id: "equilibrium",
    proofName: "高维范式",
    short: "均衡",
    description: "直接以高维信息流作为新的计算范式。",
    flavor: "变化本身成为可计算的痕迹。",
    cost: 0,
    unlockFact: "arg.memory.shown",
  },
];

export const DEFAULT_IDLE_FACTIONS: readonly IdleFactionDefinition[] = [
  { id: "elf", name: "BMD", accent: "#fe6d01", icon: "vendor-01" },
  { id: "angel", name: "Nvidiy", accent: "#99f802", icon: "vendor-02" },
  { id: "goblin", name: "Ontel", accent: "#015dca", icon: "vendor-03" },
  { id: "demon", name: "Ringo", accent: "#cbcbcb", icon: "vendor-04" },
  { id: "liuxing", name: "流形", accent: "#38bdf8", icon: "set4-07" },
];

/**
 * The simple skill definitions are enough for the recovered active-skill bar
 * and base runtime. Dynamic faction formulas remain extension-owned.
 */
export const DEFAULT_IDLE_SKILLS: readonly IdleSkillDefinition[] = [
  {
    id: "surge",
    name: "算力激增",
    scope: "universal",
    cooldownSec: 60,
    durationSec: 12,
    effect: { kind: "prodBuff", magnitude: 3, target: "all" },
  },
  {
    id: "burst",
    name: "即时结算",
    scope: "universal",
    cooldownSec: 45,
    durationSec: 0,
    effect: { kind: "lump", seconds: 30, grantsFactionCoins: 600 },
  },
  {
    id: "click_frenzy",
    name: "狂点",
    scope: "elf",
    cooldownSec: 40,
    durationSec: 12,
    effect: { kind: "clickBuff", magnitude: 12 },
  },
  {
    id: "overclock",
    name: "超频",
    scope: "angel",
    cooldownSec: 90,
    durationSec: 8,
    effect: { kind: "prodBuff", magnitude: 40, target: "all" },
  },
  {
    id: "resonance",
    name: "共振",
    scope: "angel",
    cooldownSec: 1,
    durationSec: 0,
    effect: { kind: "lump", seconds: 1.5 },
  },
  {
    id: "payday",
    name: "发薪日",
    scope: "goblin",
    cooldownSec: 40,
    durationSec: 0,
    effect: { kind: "lump", seconds: 20, grantsFactionCoins: 1_500 },
  },
  {
    id: "lightning_strike",
    name: "天降金体",
    scope: "demon",
    cooldownSec: 10,
    durationSec: 40,
    effect: {
      kind: "strike",
      magnitude: 3,
      pool: "decelerate",
      critChance: 0.15,
      critMult: 4,
    },
  },
  {
    id: "brimstone",
    name: "硫火",
    scope: "demon",
    cooldownSec: 65,
    durationSec: 12,
    effect: { kind: "prodBuff", magnitude: 4, target: "all" },
  },
];
