use super::{attachment, host::*, router, Isolate};
use futures_util::{
    future::LocalBoxFuture, lock::Mutex, stream::FuturesUnordered, FutureExt, StreamExt,
};
use nori_core::{
    config::ServerAi,
    jsonutil::canonical_json,
    session, snapshot,
    tasks::{Pacing, Step, Task},
    world::{Secrets, World},
};
use serde_json::{json, Map, Value};
use std::cell::RefCell;

pub const WORLD_KEY: &str = "nori:world:v1";
pub const AI_KEY: &str = "nori:ai-public:v1";

pub enum Frame {
    Text(String),
    Binary(Vec<u8>),
}

#[derive(Default)]
pub struct SessionObject {
    world: RefCell<Option<World>>,
    last_persisted: RefCell<Option<String>>,
    load_lock: Mutex<()>,
    persist_lock: Mutex<()>,
}

pub trait SessionHost:
    Storage + Sockets + ObjectStore + Fetch + Sleep + Clock + Bindings + Log
{
}
impl<T: Storage + Sockets + ObjectStore + Fetch + Sleep + Clock + Bindings + Log> SessionHost
    for T
{
}

impl SessionObject {
    /// Validation only; the wasm adapter creates/accepts the pair after success.
    /// Socket entropy is generated by the adapter only after this returns Ok.
    pub fn upgrade(
        host: &(impl Bindings + Clock),
        req: &Request,
    ) -> Result<std::result::Result<String, nori_core::http::HttpResponse>> {
        if let Some(response) = router::forbidden(req) {
            return Ok(Err(response));
        }
        let config = RuntimeConfig::read(host)?;
        Ok(router::validate_upgrade(
            req,
            &config.secret,
            host.now_ms() / 1000,
        ))
    }

    pub fn world_id(&self) -> Option<String> {
        self.world.borrow().as_ref().map(|w| w.world_id.clone())
    }

    async fn load_world(
        &self,
        host: &impl SessionHost,
        isolate: &Isolate,
        user: &str,
        disabled: bool,
    ) -> Result<()> {
        if self
            .world
            .borrow()
            .as_ref()
            .is_some_and(|w| w.owner_id == user)
        {
            return Ok(());
        }
        let _guard = self.load_lock.lock().await;
        if self
            .world
            .borrow()
            .as_ref()
            .is_some_and(|w| w.owner_id == user)
        {
            return Ok(());
        }
        {
            let mut loader = isolate.loader.lock().await;
            if !loader.core(host, &isolate.pack, disabled).await {
                loader.unavailable(host);
            }
        }
        let raw = host.get(WORLD_KEY).await?;
        let restored = raw
            .as_deref()
            .and_then(|raw| snapshot::world_from_snapshot_json(raw, isolate.pack.clone()))
            .filter(|w| w.owner_id == user);
        let world = match restored {
            Some(world) => {
                *self.last_persisted.borrow_mut() = raw;
                host.log(&format!(
                    "[arcade] restored hibernated world {}",
                    world.world_id
                ));
                world
            }
            None => {
                *self.last_persisted.borrow_mut() = None;
                World::new(user, None, true, isolate.pack.clone())
            }
        }
        .with_pacing(Pacing::Edge);
        *self.world.borrow_mut() = Some(world);
        Ok(())
    }

    async fn persist_world(&self, host: &impl Storage, force: bool) -> Result<()> {
        let _guard = self.persist_lock.lock().await;
        let raw =
            snapshot::world_snapshot_json(self.world.borrow().as_ref().ok_or("world missing")?);
        if force || self.last_persisted.borrow().as_deref() != Some(&raw) {
            host.put(WORLD_KEY, &raw).await?;
            *self.last_persisted.borrow_mut() = Some(raw);
        }
        Ok(())
    }

    async fn persist_ai(&self, host: &impl Storage, config: &Value) -> Result<String> {
        let raw = canonical_json(&session::public_ai_config(config));
        host.put(AI_KEY, &raw).await?;
        Ok(raw)
    }

    /// All runtime errors use the Python close code/reason; ordinary protocol
    /// errors returned by the core are direct frames and keep the socket open.
    pub async fn on_message<H: SessionHost>(
        &self,
        host: &H,
        isolate: &Isolate,
        socket: &H::Socket,
        frame: Frame,
    ) {
        if let Err(error) = self.message_inner(host, isolate, socket, frame).await {
            host.log(&format!("[arcade] hibernation message error: {error}"));
            let _ = host.close(socket, 1011, "arcade_runtime_error");
        }
    }

    async fn message_inner<H: SessionHost>(
        &self,
        host: &H,
        isolate: &Isolate,
        socket: &H::Socket,
        frame: Frame,
    ) -> Result<()> {
        let mut saved = attachment::read(host.attachment(socket));
        if attachment::scrub(&mut saved) {
            host.set_attachment(
                socket,
                &serde_json::to_string(&saved).map_err(|e| e.to_string())?,
            )?;
        }
        let config = RuntimeConfig::read(host)?;
        if config.disable_live_pack {
            isolate.pack.clear();
        }
        match attachment::text(&saved, "role").as_deref() {
            Some("media") => Ok(()), // Server-to-browser only, even binary/invalid frames.
            Some("pending_media") => {
                self.pending_media(
                    host,
                    isolate,
                    socket,
                    saved,
                    frame,
                    config.disable_live_pack,
                )
                .await
            }
            Some("main") => match frame {
                Frame::Text(raw) => {
                    self.main(host, isolate, socket, &saved, &raw, &config)
                        .await
                }
                Frame::Binary(_) => host.close(socket, 1002, "invalid_arcade_message"),
            },
            _ => host.close(socket, 1002, "invalid_arcade_message"),
        }
    }

    async fn pending_media<H: SessionHost>(
        &self,
        host: &H,
        isolate: &Isolate,
        socket: &H::Socket,
        mut saved: Map<String, Value>,
        frame: Frame,
        disabled: bool,
    ) -> Result<()> {
        let Frame::Text(raw) = frame else {
            return host.close(socket, 1002, "invalid_media_open");
        };
        let parsed: Value = match serde_json::from_str(&raw) {
            Ok(parsed) => parsed,
            Err(_) => return host.close(socket, 1002, "invalid_media_open"),
        };
        let grant = parsed
            .get("grant")
            .and_then(Value::as_str)
            .filter(|s| !s.is_empty());
        if parsed.get("type").and_then(Value::as_str) != Some("open_media") || grant.is_none() {
            return host.close(socket, 4005, "media_grant_invalid");
        }
        let Some(user) = attachment::text(&saved, "userId") else {
            return host.close(socket, 1008, "session_invalid");
        };
        self.load_world(host, isolate, &user, disabled).await?;
        let world = self.world.borrow();
        let world = world.as_ref().ok_or("world missing")?;
        if !world.has_media_grant(grant.expect("validated grant")) {
            return host.close(socket, 4005, "media_grant_invalid");
        }
        saved.insert("role".into(), json!("media"));
        saved.insert("worldId".into(), json!(world.world_id));
        host.set_attachment(
            socket,
            &serde_json::to_string(&saved).map_err(|e| e.to_string())?,
        )
    }

    async fn main<H: SessionHost>(
        &self,
        host: &H,
        isolate: &Isolate,
        socket: &H::Socket,
        saved: &Map<String, Value>,
        raw: &str,
        config: &RuntimeConfig,
    ) -> Result<()> {
        let Some(user) = attachment::text(saved, "userId").filter(|s| !s.is_empty()) else {
            return host.close(socket, 1008, "session_invalid");
        };
        self.load_world(host, isolate, &user, config.disable_live_pack)
            .await?;
        let clients = self.clients(host);
        if attachment::text(saved, "socketId").is_none_or(|s| s.is_empty()) {
            return host.close(socket, 1008, "session_invalid");
        }
        let decoded = match session::decode_frame(raw) {
            Ok(message) => message,
            Err(error) => {
                send_direct(host, socket, &error);
                return Ok(());
            }
        };
        if session::is_ping(&decoded) {
            let out = session::handle(
                self.world.borrow_mut().as_mut().ok_or("world missing")?,
                &decoded,
                &Secrets::default(),
            );
            for message in out.direct {
                send_direct(host, socket, &message);
            }
            return Ok(()); // No settings, per-frame R2 prefetch, tasks or snapshot.
        }
        isolate
            .loader
            .lock()
            .await
            .prefetch(host, &isolate.pack, &decoded)
            .await;
        let preference = saved.get("fullUnlock").and_then(Value::as_bool);
        let (message, secrets) =
            session::prepare(raw, preference).map_err(|_| "prepared decoded frame failed")?;
        let public = if message.get("type").and_then(Value::as_str) == Some("event")
            && message.get("channel").and_then(Value::as_str) == Some("nori.ai.config")
        {
            Some(nori_core::llm::sanitize_ai_config(
                message
                    .get("payload")
                    .filter(|v| v.is_object())
                    .unwrap_or(&Value::Null),
            ))
        } else {
            secrets.ai.clone()
        };
        let persisted_ai = match public {
            Some(public) => Some(self.persist_ai(host, &public).await?),
            None => None,
        };
        let out = session::handle(
            self.world.borrow_mut().as_mut().ok_or("world missing")?,
            &message,
            &secrets,
        );
        if let Some(public) = out.public_ai {
            let raw = canonical_json(&session::public_ai_config(&public));
            if persisted_ai.as_deref() != Some(&raw) {
                self.persist_ai(host, &public).await?;
            }
        }
        // A reset may have changed worldId/media membership.
        let clients = if out.force_persist {
            self.clients(host)
        } else {
            clients
        };
        broadcast(host, &clients, &out.broadcast);
        for message in &out.direct {
            send_direct(host, socket, message);
        }
        self.drain(host, socket, &config.ai, out.tasks).await?;
        self.persist_world(host, out.force_persist).await
    }

    fn clients<H: Sockets>(&self, host: &H) -> Clients<H::Socket> {
        let world = self.world.borrow();
        let Some(world) = world.as_ref() else {
            return Clients::default();
        };
        let mut main = Vec::new();
        let mut media = Vec::new();
        for socket in host.list() {
            let saved = attachment::read(host.attachment(&socket));
            if attachment::text(&saved, "userId").as_deref() != Some(&world.owner_id)
                || attachment::text(&saved, "socketId").is_none_or(|s| s.is_empty())
            {
                continue;
            }
            match attachment::text(&saved, "role").as_deref() {
                Some("main") => main.push(socket),
                Some("media")
                    if attachment::text(&saved, "worldId").as_deref() == Some(&world.world_id) =>
                {
                    media.push(socket)
                }
                _ => {}
            }
        }
        Clients { main, media }
    }

    async fn drain<H: SessionHost>(
        &self,
        host: &H,
        origin: &H::Socket,
        ai: &ServerAi,
        tasks: Vec<Task>,
    ) -> Result<()> {
        // One async future per task step: Sleep/Http release the world borrow,
        // and Spawn inserts child + parent into the same concurrent work set.
        let mut active: FuturesUnordered<LocalBoxFuture<'_, Result<Tick>>> =
            FuturesUnordered::new();
        for task in tasks {
            active.push(self.tick(host, origin, ai, task, None).boxed_local());
        }
        while let Some(tick) = active.next().await {
            match tick? {
                Tick::Continue(task, input) => {
                    active.push(self.tick(host, origin, ai, task, input).boxed_local())
                }
                Tick::Spawn(parent, child) => {
                    active.push(self.tick(host, origin, ai, child, None).boxed_local());
                    active.push(self.tick(host, origin, ai, parent, None).boxed_local());
                }
                Tick::Done => {}
            }
        }
        Ok(()) // Including real synthesis: inline, before the one snapshot write.
    }

    async fn tick<H: SessionHost>(
        &self,
        host: &H,
        origin: &H::Socket,
        ai: &ServerAi,
        mut task: Task,
        input: Option<nori_core::provider::HttpResult>,
    ) -> Result<Tick> {
        let step = task.poll(
            self.world.borrow_mut().as_mut().ok_or("world missing")?,
            ai,
            input,
        );
        let mut input = None;
        match step {
            Step::Sleep(ms) => host.sleep(ms).await,
            Step::Http(request) => input = Some(host.fetch(request).await),
            // A socket may have joined while another task awaited Http/Sleep.
            Step::Broadcast(messages) => broadcast(host, &self.clients(host), &messages),
            Step::Media(bytes) => {
                for socket in self.clients(host).media {
                    let _ = host.send_binary(&socket, &bytes);
                }
            }
            Step::Direct(message) => send_direct(host, origin, &message),
            Step::Spawn(child) => return Ok(Tick::Spawn(task, child)),
            Step::Done => return Ok(Tick::Done),
        }
        Ok(Tick::Continue(task, input))
    }

    pub fn on_close<H: Sockets>(
        &self,
        host: &H,
        socket: &H::Socket,
        code: u16,
        reason: &str,
        _was_clean: bool,
    ) {
        let _ = host.close(socket, code, reason);
    }

    pub fn on_error(&self, host: &impl Log, error: &str) {
        host.log(&format!("[arcade] WebSocket error: {error}"));
    }
}

struct Clients<S> {
    main: Vec<S>,
    media: Vec<S>,
}

impl<S> Default for Clients<S> {
    fn default() -> Self {
        Self {
            main: Vec::new(),
            media: Vec::new(),
        }
    }
}

enum Tick {
    Continue(Task, Option<nori_core::provider::HttpResult>),
    Spawn(Task, Task),
    Done,
}

fn send_direct<H: Sockets>(host: &H, socket: &H::Socket, message: &Value) {
    if let Ok(text) = serde_json::to_string(message) {
        let _ = host.send_text(socket, &text);
    }
}

fn broadcast<H: Sockets>(host: &H, clients: &Clients<H::Socket>, messages: &[Value]) {
    let frames: Vec<_> = messages
        .iter()
        .map(|m| serde_json::to_string(m).expect("JSON wire message"))
        .collect();
    for socket in &clients.main {
        for frame in &frames {
            if host.send_text(socket, frame).is_err() {
                break;
            }
        }
    }
}
